-- SEED DATA FOR PRODUCTS (40 items)
INSERT INTO Products (ProductName, CategoryID, Price, Inventory, ImageURL, Ingredients, IsActive) VALUES
(N'Phở Bò', 1, 70000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Bún Chả', 1, 100000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Bún Bò Huế', 1, 80000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Cơm Tấm', 1, 90000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Gỏi Cuốn', 1, 100000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Bánh Mì Thịt', 1, 70000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Bánh Xèo', 1, 30000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Cơm Chiên Hải Sản', 1, 80000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Mì Quảng', 1, 50000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Hủ Tiếu Nam Vang', 1, 70000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Gà Rán', 1, 80000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Pizza Hải Sản', 1, 90000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Burger Bò', 1, 70000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Mì Ý Sốt Bò Băm', 1, 100000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Sushi Thập Cẩm', 1, 40000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Salad Cá Hồi', 1, 90000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Bò Bít Tết', 1, 90000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Cơm Cà Ri Gà', 1, 30000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Canh Chua Cá Lóc', 1, 50000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Thịt Kho Tàu', 1, 80000, 100, '🍲', N'Nguyên liệu tươi ngon, chế biến đậm đà', 1),
(N'Trà Sữa Trân Châu', 2, 20000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Cà Phê Sữa Đá', 2, 30000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Trà Đào Cam Sả', 2, 30000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Sinh Tố Bơ', 2, 20000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Nước Ép Dưa Hấu', 2, 40000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Trà Vải', 2, 30000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Trà Xanh Matcha', 2, 30000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Soda Chanh Dây', 2, 30000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Nước Ép Táo', 2, 20000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Sinh Tố Xoài', 2, 20000, 100, '🥤', N'Nước trái cây tươi, trà đậm vị', 1),
(N'Bánh Tráng Trộn', 3, 30000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Khoai Tây Chiên', 3, 30000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Gà Xiên Que', 3, 40000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Xúc Xích Đức', 3, 30000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Bánh Tráng Nướng', 3, 40000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Bắp Xào Trứng Muối', 3, 30000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Phô Mai Que', 3, 10000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Bánh Bao Chiên', 3, 30000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Há Cảo Hấp', 3, 40000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1),
(N'Chả Giò', 3, 10000, 100, '🍟', N'Ăn vặt giòn rụm, hấp dẫn', 1);

-- SEED DATA FOR REVIEWS (Randomly generated for products)
-- Lưu ý: Phải có ít nhất UserID=1 và OrderID=1 trong DB để chạy insert Reviews. Hãy đảm bảo điều kiện này hoặc sửa lại ID cho phù hợp.
INSERT INTO Reviews (UserID, ProductID, OrderID, Rating, Comment, IsHidden) VALUES
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 39 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 39 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 38 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 37 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 37 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 36 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 35 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 35 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 34 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 33 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 33 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 33 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 32 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 32 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 31 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 31 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 30 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 30 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 29 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 28 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 27 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 27 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 26 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 26 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 25 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 25 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 25 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 24 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 23 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 23 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 22 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 21 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 21 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 21 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 20 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 20 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 19 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 18 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 18 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 17 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 16 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 16 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 15 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 15 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 15 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 14 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 14 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 13 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 13 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 13 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 12 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 11 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 10 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 10 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Sẽ giới thiệu cho bạn bè.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 9 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 9 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 9 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 8 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 8 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 8 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 7 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 7 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 7 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 6 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 5 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 5 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 4 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 4 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 3 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Tuyệt vời, sẽ ủng hộ tiếp.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Rất ngon!', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Món ăn khá ổn.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY), 1, 4, N'Đóng gói cẩn thận, vị vừa miệng.', 0),
(1, (SELECT ProductID FROM Products ORDER BY ProductID DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY), 1, 5, N'Đóng gói cẩn thận, vị vừa miệng.', 0);
